# Load Dataset

In [1]:
import pandas as pd

### load txt file

In [2]:
pd.read_csv(r'C:\Users\hakim\OneDrive\Desktop\sample.txt')

  name  age  salary
0    A   23   34000
1    B   33   45000
2    C   45   78000

### load a txt file without header

In [5]:
pd.read_csv(r'C:\Users\hakim\OneDrive\Desktop\sample_2.txt')

   A  23  34000
0  B  33  45000
1  C  45  78000

In [6]:
pd.read_csv(r'C:\Users\hakim\OneDrive\Desktop\sample_2.txt',header=None)

   0   1      2
0  A  23  34000
1  B  33  45000
2  C  45  78000

In [9]:
d = pd.read_csv(r'C:\Users\hakim\OneDrive\Desktop\sample_2.txt',header=None)
d

   0   1      2
0  A  23  34000
1  B  33  45000
2  C  45  78000

In [12]:
d.columns =['Name','Age','Salary']

In [13]:
d

  Name  Age  Salary
0    A   23   34000
1    B   33   45000
2    C   45   78000

### load data with tab \t

In [14]:
pd.read_csv(r'C:\Users\hakim\OneDrive\Desktop\sample_3.txt')

  Name\tAge\tSalary
0      A\t23\t34000
1      B\t33\t45000
2      C\t45\t78000

In [15]:
pd.read_csv(r'C:\Users\hakim\OneDrive\Desktop\sample_3.txt',sep='\t')

  Name  Age  Salary
0    A   23   34000
1    B   33   45000
2    C   45   78000

### load tsv(tab separated values) file

In [17]:
pd.read_csv(r'C:\Users\hakim\OneDrive\Desktop\sample_4.tsv',sep='\t')

  Name  Age  Salary
0    A   23   34000
1    B   33   45000
2    C   45   78000

### load a file with \n

In [18]:
pd.read_csv(r'C:\Users\hakim\OneDrive\Desktop\sample_5.txt')

  name\nage\nsalary
0      A\n23\n34000
1      B\n33\n45000
2      C\n45\n78000

In [24]:
pd.read_csv(r'C:\Users\hakim\OneDrive\Desktop\sample_5.txt',sep='\n')

  name\nage\nsalary
0      A\n23\n34000
1      B\n33\n45000
2      C\n45\n78000

In [29]:
pd.read_csv(r'C:\Users\hakim\OneDrive\Desktop\sample.txt')

      A   23   34000
0  name  age  salary
1     B   33   45000
2     C   45   78000

In [30]:
pd.read_csv(r'C:\Users\hakim\OneDrive\Desktop\sample.txt',header=1)

  name  age  salary
0    B   33   45000
1    C   45   78000

### load dataset from github

In [31]:
pd.read_csv('https://raw.githubusercontent.com/KeithGalli/disney-data-science-tasks/master/dataset/disney_movie_data_final.csv')

,Unnamed: 0,title,Production company,Release date,Running time,Country,Language,Running time (int),Budget (float),Box office (float),...,Box office,Story by,Narrated by,Cinematography,Edited by,Screenplay by,Production companies,Adaptation by,Traditional,Simplified
0,0,Academy Award Review of,Walt Disney Productions,"['May 19, 1937']",41 minutes (74 minutes 1966 release),United States,English,41.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Snow White and the Seven Dwarfs,Walt Disney Productions,"['December 21, 1937 ( Carthay Circle Theatre ,...",83 minutes,United States,English,83.0,1490000.0,418000000.0,...,$418 million,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Pinocchio,Walt Disney Productions,"['February 7, 1940 ( Center Theatre )', 'Febru...",88 minutes,United States,English,88.0,2600000.0,164000000.0,...,$164 million,"['Ted Sears', 'Otto Englander', 'Webb Smith', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Fantasia,Walt Disney Productions,"['November 13, 1940']",126 minutes,United States,English,126.0,2280000.0,83300000.0,...,$76.4–$83.3 million,"['Joe Grant', 'Dick Huemer']",Deems Taylor,James Wong Howe,NaN,NaN,NaN,NaN,NaN,NaN
4,4,The Reluctant Dragon,Walt Disney Productions,"['June 20, 1941']",74 minutes,United States,English,74.0,600000.0,960000.0,...,"$960,000 (worldwide rentals)",NaN,NaN,Bert Giennon,Paul Weatherwax,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,427,Soul,"['Walt Disney Pictures', 'Pixar Animation Stud...","['October 15, 2020 ( Rome Film Festival )', 'N...",NaN,United States,English,NaN,150000000.0,NaN,...,NaN,Pete Docter,NaN,NaN,NaN,"['Pete Docter', 'Mike Jones', 'Kemp Powers']",NaN,NaN,NaN,NaN
428,428,Raya and the Last Dragon,"['Walt Disney Pictures', 'Walt Disney Animatio...","['March 12, 2021']",NaN,United States,English,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429,429,Cruella,"['Walt Disney Pictures', 'Gunn Films', 'Marc P...","['May 28, 2021 (United States)']",NaN,United States,English,NaN,NaN,NaN,...,NaN,NaN,NaN,Nicolas Karakatsanis,Tatiana S. Riegel,"['Aline Brosh McKenna', 'Jez Butterworth', 'Da...",NaN,NaN,NaN,NaN
430,430,Jungle Cruise,"['Walt Disney Pictures', 'Davis Entertainment'...","['July 30, 2021 (United States)']",NaN,United States,English,NaN,NaN,NaN,...,NaN,"['Glenn Ficarra', 'John Requa']",NaN,Flavio Labiano,Joel Negron,"['Michael Green', 'Glenn Ficarra', 'John Requa']",NaN,NaN,NaN,NaN
431,431,The Beatles: Get Back,NaN,['27 August 2021'],NaN,"['United Kingdom', 'New Zealand', 'United Stat...",English,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Jabez Olssen,NaN,"['Walt Disney Pictures', 'Apple Corps', 'WingN...",NaN,NaN,NaN

In [32]:
pd.read_csv('https://raw.githubusercontent.com/pomber/covid19/master/test/data/time_series_covid19_confirmed_global.csv')

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,3/16/20,3/17/20,3/18/20,3/19/20,3/20/20,3/21/20,3/22/20,3/23/20,3/24/21,3/25/21
0,NaN,Afghanistan,33.000000,65.000000,0,0,0,0,0,0,...,21,22,22,22,24,24,40,40,74,84
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,51,55,59,64,70,76,89,104,123,146
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,54,60,74,87,90,139,201,230,264,302
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,2,39,39,53,75,88,113,133,164,188
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,0,0,0,0,1,2,2,3,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240,NaN,Libya,26.335100,17.228331,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
241,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,38,39,41,44,47,48,52,59,59,-1
242,NaN,Guinea-Bissau,11.803700,-15.180400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
243,NaN,Mali,17.570692,-3.996166,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
244,NaN,Saint Kitts and Nevis,17.357822,-62.782998,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2

As disney dataset contains 400+ rows
but if i want to read only 50 rows

In [35]:
pd.read_csv('https://raw.githubusercontent.com/KeithGalli/disney-data-science-tasks/master/dataset/disney_movie_data_final.csv',nrows=50)

,Unnamed: 0,title,Production company,Release date,Running time,Country,Language,Running time (int),Budget (float),Box office (float),...,Box office,Story by,Narrated by,Cinematography,Edited by,Screenplay by,Production companies,Adaptation by,Traditional,Simplified
0,0,Academy Award Review of,Walt Disney Productions,"['May 19, 1937']",41 minutes (74 minutes 1966 release),United States,English,41.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Snow White and the Seven Dwarfs,Walt Disney Productions,"['December 21, 1937 ( Carthay Circle Theatre ,...",83 minutes,United States,English,83.0,1490000.0,418000000.0,...,$418 million,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Pinocchio,Walt Disney Productions,"['February 7, 1940 ( Center Theatre )', 'Febru...",88 minutes,United States,English,88.0,2600000.0,164000000.0,...,$164 million,"['Ted Sears', 'Otto Englander', 'Webb Smith', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Fantasia,Walt Disney Productions,"['November 13, 1940']",126 minutes,United States,English,126.0,2280000.0,83300000.0,...,$76.4–$83.3 million,"['Joe Grant', 'Dick Huemer']",Deems Taylor,James Wong Howe,NaN,NaN,NaN,NaN,NaN,NaN
4,4,The Reluctant Dragon,Walt Disney Productions,"['June 20, 1941']",74 minutes,United States,English,74.0,600000.0,960000.0,...,"$960,000 (worldwide rentals)",NaN,NaN,Bert Giennon,Paul Weatherwax,NaN,NaN,NaN,NaN,NaN
5,5,Dumbo,Walt Disney Productions,"['October 23, 1941 (New York City)', 'October ...",64 minutes,United States,English,64.0,950000.0,1300000.0,...,$1.3 million (est. United States/Canada rental...,"['Otto Englander', 'Joe Grant', 'Dick Huemer']",John McLeish,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6,Bambi,Walt Disney Productions,"['August 9, 1942 (World Premiere-London)', 'Au...",70 minutes,United States,English,70.0,858000.0,267400000.0,...,$267.4 million,"['Story direction', 'Perce Pearce', 'Story ada...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,Saludos Amigos,Walt Disney Productions,"['August 24, 1942 (World Premiere-Rio de Janei...",42 minutes,United States,"['English', 'Portuguese', 'Spanish']",42.0,NaN,1135000.0,...,"$1,135,000 (worldwide rentals)","['Homer Brightman', 'William Cottrell', 'Richa...",Fred Shields,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8,Victory Through Air Power,Walt Disney Productions,"['July 17, 1943']",65 min.,United States,English,65.0,788000.0,799000.0,...,"$799,000",NaN,Art Baker,Ray Rennahan,Jack Dennis,NaN,NaN,NaN,NaN,NaN
9,9,The Three Caballeros,Walt Disney Productions,"['December 21, 1944 (Mexico City)', 'February ...",71 minutes,United States,"['English', 'Spanish', 'Portuguese']",71.0,NaN,3355000.0,...,"$3,355,000 (worldwide rentals)","['Homer Brightmen', 'Ernest Terrazas', 'Ted Se...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,10,Make Mine Music,Walt Disney Productions,"['April 20, 1946 (Premiere-New York City)', 'A...",75 minutes,United States,English,75.0,1350000.0,3275000.0,...,"$3,275,000 (worldwide rentals)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,11,Song of the South,Walt Disney Productions,"['November 12, 1946 (Premiere: Atlanta, Georgi...",94 minutes,United States,English,94.0,2125000.0,65000000.0,...,$65 million,NaN,NaN,Gregg Toland,William M. Morgan,"['Live action:', 'Morton Grant', 'Maurice Rapf...",NaN,NaN,NaN,NaN
12,12,Fun and Fancy Free,Walt Disney Productions,"['September 27, 1947']",73 minutes,United States,English,73.0,NaN,3165000.0,...,"$3,165,000 (worldwide rentals)","['Homer Brightman', 'Eldon Dedini', 'Lance Nol...","['Dinah Shore ( Bongo )', 'Edgar Bergen ( Mick...",NaN,Jack Bachom,NaN,NaN,NaN,NaN,NaN
13,13,Melody Time,Walt Disney Productions,"May 27, 1948",75 minutes,United States,English,75.0,1500000.0,2560000.0,...,"$2,560,000 (worldwide rentals)",NaN,NaN,NaN,"['Donald Halliday', 'Thomas Scott']",NaN,NaN,NaN,NaN,NaN
14,14,So Dear to My Heart,Walt Disney Productions,"['November 29, 1948 (Chicago, Illinois)', 'Jan...",82 minutes,United States,English,82.0,1500000.0,3700000.0,...,"$3.7 million (U.S. rental) $575,000 (foreign r...",NaN,NaN,Winton C. Hoch,"['Lloyd L. Richardson', 'Thomas Scott']",NaN,NaN,NaN,NaN,NaN
15,15,The Adventures of Ichabod and Mr. Toad,Walt Disney Productions,"['October 5, 1949']",68 minutes,United States,English,68.0,NaN,1625000.0,...,"$1,625,000 (worldwide rentals)","['Erdman Penner', 'Winston Hibler', 'Joe Rinal...","['Basil Rathbone ( The Wind in the Willows )',...",NaN,John O. Young,NaN,NaN,NaN,NaN,NaN
16,16,Cinderella,Walt Disney Productions,"['February 15, 1950 (Boston)', 'March 4, 1950 ...",74 minutes,United States,English,74.0,2900000.0,263600000.0,...,$263.6 million,"['Ken Anderson', 'Perce Pearce', 'Homer Bright...",Betty Lou Gerson,NaN,Donald Halliday,NaN,NaN,NaN,NaN,NaN
17,17,Treasure Island,Walt Disney Productions,"['June 22, 1950 (World Premiere- London )', 'J...",96 minutes,"['United States', 'United Kingdom']",English,96.0,1800000.0,4100000.0,...,"$4,100,000 (worldwide rentals)",NaN,NaN,Freddie Young,Alan Jaggs,NaN,NaN,NaN,NaN,NaN
18,18,Alice in Wonderland,Walt Disney Productions,"['July 26, 1951 (London, premiere)', 'July 28,...",75 minutes,United States,English,75.0,3000000.0,5600000.0,...,"$5.6 million (US, 1951)","['Milt Banta', 'Del Connell', 'Bill Cottrell',...",NaN,NaN,Lloyd Richardson,NaN,NaN,NaN,NaN,NaN
19,19,The Story of Robin Hood and His Merrie Men,"['Walt Disney Productions', 'RKO Radio Picture...","['March 13, 1952 (Premiere- London )', 'June 2...",84 minutes,"['United States', 'United Kingdom']",English,84.0,NaN,2100000.0,...,$2.1 million (US rentals),NaN,NaN,Guy Green,NaN,NaN,NaN,NaN,NaN,NaN
20,20,Peter Pan,Walt Disney Productions,"['February 5, 1953 (United States)']",77 minutes,United States,English,77.0,4000000.0,87400000.0,...,$87.4 million,"['Milt Banta', 'Bill Cottrell', 'Winston Hible...",Tom Conway,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,21,The Sword and the Rose,Walt Disney Productions,"['August 8, 1953 ( US )']",92 minutes,"['United Kingdom', 'United States']",English,92.0,2000000.0,1000000.0,...,$1 million (US),NaN,NaN,Geoffrey Unsworth,Gerald Thomas,NaN,NaN,NaN,NaN,NaN
22,22,The Living Desert,Walt Disney Productions,"November 10, 1953",69 minutes,United States,English,69.0,300000.0,2600000.0,...,$2.6 million (US),NaN,Winston Hibler,"['Robert H. Crandall', 'N. Paul Kenworthy']",Norman R. Palmer,NaN,NaN,NaN,NaN,NaN
23,23,"Rob Roy, the Highland Rogue",Walt Disney Productions,"['26 October 1953 (Premiere- London )', '4 Feb...",81 minutes,"['United Kingdom', 'United States']",English,81.0,1800000.0,NaN,...,NaN,NaN,NaN,Guy Green,Geoffrey Foot,NaN,NaN,NaN,NaN,NaN
24,24,The Vanishing Prairie,Walt Disney Productions,"['August 17, 1954']","['60 minutes (VHS version)', '71 minutes (orig...",United States,English,60.0,NaN,1750000.0,...,$1.75 million (US and Canadian rentals),NaN,Winston Hibler,N. Paul Kenworthy,Lloyd L. Richardson,NaN,NaN,NaN,NaN,NaN
25,25,"20,000 Leagues Under the Sea",Walt Disney Productions,"['December 23, 1954']",127 minutes,United States,English,127.0,5000000.0,28200000.0,...,$28.2 million,NaN,NaN,Franz Planer,Elmo Williams,Earl Felton,NaN,NaN,NaN,NaN
26,26,"Davy Crockett, King of the Wild Frontier",Walt Disney Productions,"May 25, 1955",92 minutes,United States,English,92.0,NaN,2150000.0,...,"$2,150,000 (US)",NaN,NaN,Charles P. Boyle,Chester W. Schaeffer,NaN,NaN,NaN,NaN,NaN
27,27,Lady and the Tramp,Walt Disney Productions,"['June 22, 1955']",76 minutes,United States,English,76.0,4000000.0,187000000.0,...,$187 million,"['Erdman Penner', 'Joe Rinaldi', 'Ralph Wright...",NaN,NaN,Don Halliday,NaN,NaN,NaN,NaN,NaN
28,28,The African Lion,Walt Disney Productions,"['September 14, 1955']",75 minutes,United States,English,75.0,NaN,2100000.0,...,$2.1 million (US),NaN,Winston Hibler,"['Alfred Milotte', 'Elma Milotte']",Norman R. Palmer,NaN,NaN,NaN,NaN,NaN
29,29,The Littlest Outlaw,Walt Disney Productions,"December 22, 1955",73 minutes,"United States, Mexico","English, Spanish",73.0,NaN,1600000.0,...,$1.6 million (US),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,30,The Great Locomotive Chase,Walt Disney Productions,"June 8, 1956",85 minutes,United States,English,85.0,NaN,1700000.0,...,$1.7 million (US),NaN,NaN,Charles Boyle,Ellsworth Hoagland,NaN,NaN,NaN,NaN,NaN
31,31,Davy Crockett and the River Pirates,Walt Disney Productions,"July 18, 1956",81 minutes,United States,English,81.0,NaN,NaN,...,NaN,NaN,NaN,NaN,Stanley Johnson,NaN,NaN,NaN,NaN,NaN
32,32,Secrets of Life,Walt Disney Productions,"['November 6, 1956']",70 minutes,United States,English,70.0,NaN,NaN,...,NaN,NaN,Winston Hibler,"['William A. Anderson', 'Arthur Carter', 'Jack...",Anthony Gerard,NaN,NaN,NaN,NaN,NaN
33,33,Westward Ho the Wagons!,Walt Disney Productions,"['December 20, 1956']",90 min.,United States,English,90.0,NaN,2750000.0,...,$2.75 million (US),NaN,NaN,"Charles P. Boyle , A.S.C.","Cotton Warburton , A.C.E.",Tom Blackburn,NaN,NaN,NaN,NaN
34,34,Johnny Tremain,Walt Disney Productions,"June 19, 1957",80 minutes,United States,English,80.0,700000.0,NaN,...,NaN,NaN,NaN,Charles P. Boyle,Stanley E. Johnson,NaN,NaN,NaN,NaN,NaN
35,35,Perri,Walt Disney Productions,"August 28, 1957",75 minutes,United States,English,75.0,NaN,1750000.0,...,$1.75 million (US rentals),NaN,Winston Hibler,NaN,Jack Atwood,NaN,NaN,NaN,NaN,NaN
36,36,Old Yeller,Walt Disney Productions,"['December 25, 1957']",83 minutes,United States,English,83.0,NaN,6250000.0,...,"$6,250,000 (US/Canada rentals)",NaN,NaN,Charles P. Boyle,Stanley E. Johnson,"['Fred Gipson', 'William Tunberg']",NaN,NaN,NaN,NaN
37,37,The Light in the Forest,Walt Disney Productions,"['July 9, 1958']",83 minutes,United States,English,83.0,NaN,NaN,...,NaN,NaN,NaN,Ellsworth Fredericks,NaN,NaN,NaN,NaN,NaN,NaN
38,38,White Wilderness,Walt Disney Productions,"['August 12, 1958']",72 minutes,"['United States', 'Canada']",English,72.0,NaN,1800000.0,...,$1.8 million (est. US/ Canada rentals),NaN,Winston Hibler,NaN,Norman R. Palmer,NaN,NaN,NaN,NaN,NaN
39,39,Tonka,Walt Disney Productions,"['December 25, 1958']",97 minutes,United States,English,97.0,NaN,2500000.0,...,$2.5 million (est. US/ Canada rentals),NaN,NaN,Loyal Griggs,Ellsworth Hoagland,NaN,NaN,NaN,NaN,NaN
40,40,Sleeping Beauty,Walt Disney Productions,"['January 29, 1959']",75 minutes,United States,English,75.0,6000000.0,51600000.0,...,$51.6 million (United States/Canada),"['Milt Banta', 'Winston Hibler', 'Bill Peet', ...",Marvin Miller,NaN,"['Roy M. Brewer Jr.', 'Donald Halliday']",NaN,NaN,NaN,NaN,NaN
41,41,The Shaggy Dog,Walt Disney Productions,"['March 19, 1959']",104 minutes,United States,English,104.0,1000000.0,12300000.0,...,$12.3 million (US and Canada rentals),NaN,Paul Frees (opening only),Edward Colman,James Ballas,NaN,NaN,NaN,NaN,NaN
42,42,Darby O'Gill and the Little People,Walt Disney Productions,"['June 24, 1959 (Dublin)', 'June 26, 1959 (Los...",93 minutes,United States,"['English', 'Irish']",93.0,NaN,NaN,...,"['Original release', ':', '$2.6 million (est. ...",NaN,NaN,Winton Hoch,Stanley Johnson,NaN,NaN,NaN,NaN,NaN
43,43,Third Man on the Mountain,Walt Disney Productions,"['November 10, 1959']",105 minutes,United States,English,105.0,2000000.0,1700000.0,...,"$1,700,000 (US/Canada rentals)",NaN,NaN,Harry Waxman,NaN,NaN,NaN,NaN,NaN,NaN
44,44,Toby Tyler,Walt Disney Productions,"January 21, 1960 ( Sarasota, FL )",95 minutes,United States,English,95.0,NaN,3100000.0,...,"$3,100,000 (US/Canada rentals)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,45,Kidnapped,Walt Disney Productions,"['February 24, 1960']",97 minutes,United States,"English, Scots",97.0,NaN,NaN,...,NaN,NaN,NaN,Paul Beeson,Gordon Stone,NaN,NaN,NaN,NaN,NaN
46,46,Pollyanna,Walt Disney Productions,"May 19, 1960",134 minutes,United States,English,134.0,2500000.0,3750000.0,...,$3.75 million (US and Canadian rentals),NaN,NaN,Russell Harlan,Frank Gross,David Swift,NaN,NaN,NaN,NaN
47,47,Jungle Cat,Walt Disney Productions,"['August 10, 1960']",69 minutes,United States,English,69.0,NaN,2300000.0,...,$2.3 million (US and Canadian rentals),NaN,Winston Hibler,"['Lloyd Beebe', 'James R. Simon', 'Hugh A. Wil...",Norman R. Palmer,NaN,NaN,NaN,NaN,NaN
48,48,Ten Who Dared,Walt Disney Productions,"['November 1, 1960']",92 minutes,United States,English,92.0,NaN,NaN,...,NaN,NaN,NaN,Gordon Avil,"['Norman Palmer', 'Cotton Warburton']",NaN,NaN,NaN,NaN,NaN
49,49,Swiss Family Robinson,Walt Disney Productions,"['December 21, 1960']",126 minutes,United States,English,126.0,4000000.0,40000000.0,...,$40 million,NaN,NaN,Harry Waxman,Peter Boita,NaN,NaN,NaN,NaN,NaN

From disney dataset if specific columns we are interested to read

In [37]:
pd.read_csv('https://raw.githubusercontent.com/KeithGalli/disney-data-science-tasks/master/dataset/disney_movie_data_final.csv',
           usecols=['title','Country'])

,title,Country
0,Academy Award Review of,United States
1,Snow White and the Seven Dwarfs,United States
2,Pinocchio,United States
3,Fantasia,United States
4,The Reluctant Dragon,United States
...,...,...
427,Soul,United States
428,Raya and the Last Dragon,United States
429,Cruella,United States
430,Jungle Cruise,United States
431,The Beatles: Get Back,"['United Kingdom', 'New Zealand', 'United Stat..."

In [49]:
df = pd.read_csv('https://raw.githubusercontent.com/KeithGalli/disney-data-science-tasks/master/dataset/disney_movie_data_final.csv',
           chunksize=100)
df

In [50]:
for i in df:
    print(i.shape)

(100, 32)
(100, 32)
(100, 32)
(100, 32)
(32, 32)

In [7]:
pd.read_csv(r'C:\Users\hakim\OneDrive\Desktop\sample_5.txt',delimiter="\n")

  name\nage\nsalary
0      A\n23\n34000
1      B\n33\n45000
2      C\n45\n78000