## Splitting Strategy

In [1]:
from sklearn.datasets import load_boston

In [5]:
bs = load_boston()
bs

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
        19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
        20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
        23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
        33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
        21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
        20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
        23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
        15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21.5, 19.6, 15.3, 19.4,
        17. , 15.6, 13.1, 41.3, 24.3, 23.3, 27. , 50. , 50. , 50. , 22.7,
        25. , 50. , 23.8, 23.8, 22.3, 17.4, 19.1, 23.1, 23.6, 22.6, 29.4,
        23.2, 24.6, 29.9, 37.2, 39.8, 36.2, 37.9, 32.5, 26.4, 29.6, 50. ,
        32. , 29.8, 34.9, 37. , 30.5, 36.4, 31.1, 29.1, 50. , 33.3, 30.3,
        34.6, 34.9, 32.9, 24.1, 42.3, 48.5, 50. , 22.6, 24.4, 22.5, 24.4,
        20. , 21.7, 19.3, 22.4, 28.1, 23.7, 25. , 23.3, 28.7, 21.5, 23. ,
        26.7, 21.7, 27.5, 30.1, 44.8, 50. , 37.6, 31.6, 46.7, 31.5, 24.3,
        31.7, 41.7, 48.3, 29. , 24. , 25.1, 31.5, 23.7, 23.3, 22. , 20.1,
        22.2, 23.7, 17.6, 18.5, 24.3, 20.5, 24.5, 26.2, 24.4, 24.8, 29.6,
        42.8, 21.9, 20.9, 44. , 50. , 36. , 30.1, 33.8, 43.1, 48.8, 31. ,
        36.5, 22.8, 30.7, 50. , 43.5, 20.7, 21.1, 25.2, 24.4, 35.2, 32.4,
        32. , 33.2, 33.1, 29.1, 35.1, 45.4, 35.4, 46. , 50. , 32.2, 22. ,
        20.1, 23.2, 22.3, 24.8, 28.5, 37.3, 27.9, 23.9, 21.7, 28.6, 27.1,
        20.3, 22.5, 29. , 24.8, 22. , 26.4, 33.1, 36.1, 28.4, 33.4, 28.2,
        22.8, 20.3, 16.1, 22.1, 19.4, 21.6, 23.8, 16.2, 17.8, 19.8, 23.1,
        21. , 23.8, 23.1, 20.4, 18.5, 25. , 24.6, 23. , 22.2, 19.3, 22.6,
        19.8, 17.1, 19.4, 22.2, 20.7, 21.1, 19.5, 18.5, 20.6, 19. , 18.7,
        32.7, 16.5, 23.9, 31.2, 17.5, 17.2, 23.1, 24.5, 26.6, 22.9, 24.1,
        18.6, 30.1, 18.2, 20.6, 17.8, 21.7, 22.7, 22.6, 25. , 19.9, 20.8,
        16.8, 21.9, 27.5, 21.9, 23.1, 50. , 50. , 50. , 50. , 50. , 13.8,
        13.8, 15. , 13.9, 13.3, 13.1, 10.2, 10.4, 10.9, 11.3, 12.3,  8.8,
         7.2, 10.5,  7.4, 10.2, 11.5, 15.1, 23.2,  9.7, 13.8, 12.7, 13.1,
        12.5,  8.5,  5. ,  6.3,  5.6,  7.2, 12.1,  8.3,  8.5,  5. , 11.9,
        27.9, 17.2, 27.5, 15. , 17.2, 17.9, 16.3,  7. ,  7.2,  7.5, 10.4,
         8.8,  8.4, 16.7, 14.2, 20.8, 13.4, 11.7,  8.3, 10.2, 10.9, 11. ,
         9.5, 14.5, 14.1, 16.1, 14.3, 11.7, 13.4,  9.6,  8.7,  8.4, 12.8,
        10.5, 17.1, 18.4, 15.4, 10.8, 11.8, 14.9, 12.6, 14.1, 13. , 13.4,
        15.2, 16.1, 17.8, 14.9, 14.1, 12.7, 13.5, 14.9, 20. , 16.4, 17.7,
        19.5, 20.2, 21.4, 19.9, 19. , 19.1, 19.1, 20.1, 19.9, 19.6, 23.2,
        29.8, 13.8, 13.3, 16.7, 12. , 14.6, 21.4, 23. , 23.7, 25. , 21.8,
        20.6, 21.2, 19.1, 20.6, 15.2,  7. ,  8.1, 13.6, 20.1, 21.8, 24.5,
        23.1, 19.7, 18.3, 21.2, 17.5, 16.8, 22.4, 20.6, 23.9, 22. , 11.9]),
 'feature_names': array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
        'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7'),
 'DESCR': ".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per $10,000\n        - PTRATIO  pupil-teacher ratio by town\n        - B        1000(Bk - 0.63)^2 where Bk is the proportion of black people by town\n        - LSTAT    % lower status of the population\n        - MEDV     Median value of owner-occupied homes in $1000's\n\n    :Missing Attribute Values: None\n\n    :Creator: Harrison, D. and Rubinfeld, D.L.\n\nThis is a copy of UCI ML housing dataset.\nhttps://archive.ics.uci.edu/ml/machine-learning-databases/housing/\n\n\nThis dataset was taken from the StatLib library which is maintained at Carnegie Mellon University.\n\nThe Boston house-price data of Harrison, D. and Rubinfeld, D.L. 'Hedonic\nprices and the demand for clean air', J. Environ. Economics & Management,\nvol.5, 81-102, 1978.   Used in Belsley, Kuh & Welsch, 'Regression diagnostics\n...', Wiley, 1980.   N.B. Various transformations are used in the table on\npages 244-261 of the latter.\n\nThe Boston house-price data has been used in many machine learning papers that address regression\nproblems.   \n     \n.. topic:: References\n\n   - Belsley, Kuh & Welsch, 'Regression diagnostics: Identifying Influential Data and Sources of Collinearity', Wiley, 1980. 244-261.\n   - Quinlan,R. (1993). Combining Instance-Based and Model-Based Learning. In Proceedings on the Tenth International Conference of Machine Learning, 236-243, University of Massachusetts, Amherst. Morgan Kaufmann.\n",
 'filename': 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn\\datasets\\data\\boston_house_prices.csv'}

In [8]:
import pandas as pd
# create an input dataframe
df = pd.DataFrame(bs.data,columns=bs.feature_names)
df[:2]

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.9,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.9,9.14

In [11]:
bs.target[:2]

array([24. , 21.6])

In [9]:
# Add output 
df['price'] = bs.target

In [10]:
df.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'price'],
      dtype='object')

## When we have a single file/dataset the we need to segment the dataset
## into training data and testing data

In [12]:
df.shape

(506, 14)

In [ ]:
# traditional splitting strategies
# 80% for traiing - 20% testing
# 70% for training - 30% for testing

In [13]:
# 80% for traiing - 20% testing
#training: input + output
506*.8

404.8

In [14]:
#testing : input + output
506*.2

101.2

In [19]:
# separate input and output from df
X = df.drop(columns='price')
y = df.price

In [22]:
display(X[:2],y[:2])

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.9,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.9,9.14

0    24.0
1    21.6
Name: price, dtype: float64

In [26]:
# when we r not supplying train_size and test_size so theyr set to None
#means for trianing 75% and testing 25%
display(506*.75,506*.25)

379.5

126.5

In [16]:
#import a function to split
from sklearn.model_selection import train_test_split

In [23]:
train_test_split(X,y)

[        CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS   RAD    TAX  \
 261  0.53412  20.0   3.97   0.0  0.647  7.520   89.4  2.1398   5.0  264.0
 8    0.21124  12.5   7.87   0.0  0.524  5.631  100.0  6.0821   5.0  311.0
 190  0.09068  45.0   3.44   0.0  0.437  6.951   21.5  6.4798   5.0  398.0
 207  0.25199   0.0  10.59   0.0  0.489  5.783   72.7  4.3549   4.0  277.0
 200  0.01778  95.0   1.47   0.0  0.403  7.135   13.9  7.6534   3.0  402.0
 ..       ...   ...    ...   ...    ...    ...    ...     ...   ...    ...
 473  4.64689   0.0  18.10   0.0  0.614  6.980   67.6  2.5329  24.0  666.0
 243  0.12757  30.0   4.93   0.0  0.428  6.393    7.8  7.0355   6.0  300.0
 152  1.12658   0.0  19.58   1.0  0.871  5.012   88.0  1.6102   5.0  403.0
 402  9.59571   0.0  18.10   0.0  0.693  6.404  100.0  1.6390  24.0  666.0
 362  3.67822   0.0  18.10   0.0  0.770  5.362   96.2  2.1036  24.0  666.0

      PTRATIO       B  LSTAT
 261     13.0  388.37   7.26
 8       15.2  386.63  29.93
 190     15.2  377.68   5.10
 207     18.6  389.43  18.06
 200     17.0  384.30   4.45
 ..       ...     ...    ...
 473     20.2  374.68  11.66
 243     16.6  374.71   5.19
 152     14.7  343.28  12.12
 402     20.2  376.11  20.31
 362     20.2  380.79  10.19

 [379 rows x 13 columns],
         CRIM   ZN  INDUS  CHAS    NOX     RM   AGE     DIS   RAD    TAX  \
 457  8.20058  0.0  18.10   0.0  0.713  5.936  80.3  2.7792  24.0  666.0
 295  0.12932  0.0  13.92   0.0  0.437  6.678  31.1  5.9604   4.0  289.0
 339  0.05497  0.0   5.19   0.0  0.515  5.985  45.4  4.8122   5.0  224.0
 95   0.12204  0.0   2.89   0.0  0.445  6.625  57.8  3.4952   2.0  276.0
 87   0.07151  0.0   4.49   0.0  0.449  6.121  56.8  3.7476   3.0  247.0
 ..       ...  ...    ...   ...    ...    ...   ...     ...   ...    ...
 311  0.79041  0.0   9.90   0.0  0.544  6.122  52.8  2.6403   4.0  304.0
 366  3.69695  0.0  18.10   0.0  0.718  4.963  91.4  1.7523  24.0  666.0
 486  5.69175  0.0  18.10   0.0  0.583  6.114  79.8  3.5459  24.0  666.0
 43   0.15936  0.0   6.91   0.0  0.448  6.211   6.5  5.7209   3.0  233.0
 322  0.35114  0.0   7.38   0.0  0.493  6.041  49.9  4.7211   5.0  287.0

      PTRATIO       B  LSTAT
 457     20.2    3.50  16.94
 295     16.0  396.90   6.27
 339     20.2  396.90   9.74
 95      18.0  357.98   6.65
 87      18.5  395.15   8.44
 ..       ...     ...    ...
 311     18.4  396.90   5.98
 366     20.2  316.03  14.00
 486     20.2  392.68  14.98
 43      17.9  394.46   7.44
 322     19.6  396.90   7.70

 [127 rows x 13 columns],
 261    43.1
 8      16.5
 190    37.0
 207    22.5
 200    32.9
        ...
 473    29.8
 243    23.7
 152    15.3
 402    12.1
 362    20.8
 Name: price, Length: 379, dtype: float64,
 457    13.5
 295    28.6
 339    19.0
 95     28.4
 87     22.2
        ...
 311    22.1
 366    21.9
 486    19.1
 43     24.7
 322    20.4
 Name: price, Length: 127, dtype: float64]

In [27]:
# Now wil specify 80% for training
train_test_split(X,y,train_size=.8)

[         CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS   RAD    TAX  \
 251   0.21409  22.0   5.86   0.0  0.431  6.438    8.9  7.3967   7.0  330.0
 422  12.04820   0.0  18.10   0.0  0.614  5.648   87.6  1.9512  24.0  666.0
 153   2.14918   0.0  19.58   0.0  0.871  5.709   98.5  1.6232   5.0  403.0
 178   0.06642   0.0   4.05   0.0  0.510  6.860   74.4  2.9153   5.0  296.0
 202   0.02177  82.5   2.03   0.0  0.415  7.610   15.7  6.2700   2.0  348.0
 ..        ...   ...    ...   ...    ...    ...    ...     ...   ...    ...
 259   0.65665  20.0   3.97   0.0  0.647  6.842  100.0  2.0107   5.0  264.0
 155   3.53501   0.0  19.58   1.0  0.871  6.152   82.6  1.7455   5.0  403.0
 409  14.43830   0.0  18.10   0.0  0.597  6.852  100.0  1.4655  24.0  666.0
 362   3.67822   0.0  18.10   0.0  0.770  5.362   96.2  2.1036  24.0  666.0
 113   0.22212   0.0  10.01   0.0  0.547  6.092   95.4  2.5480   6.0  432.0

      PTRATIO       B  LSTAT
 251     19.1  377.07   3.59
 422     20.2  291.55  14.10
 153     14.7  261.95  15.79
 178     16.6  391.27   6.92
 202     14.7  395.38   3.11
 ..       ...     ...    ...
 259     13.0  391.93   6.90
 155     14.7   88.01  15.02
 409     20.2  179.36  19.78
 362     20.2  380.79  10.19
 113     17.8  396.90  17.09

 [404 rows x 13 columns],
          CRIM    ZN  INDUS  CHAS     NOX     RM    AGE     DIS   RAD    TAX  \
 304   0.05515  33.0   2.18   0.0  0.4720  7.236   41.1  4.0220   7.0  222.0
 121   0.07165   0.0  25.65   0.0  0.5810  6.004   84.1  2.1974   2.0  188.0
 337   0.03041   0.0   5.19   0.0  0.5150  5.895   59.6  5.6150   5.0  224.0
 190   0.09068  45.0   3.44   0.0  0.4370  6.951   21.5  6.4798   5.0  398.0
 204   0.02009  95.0   2.68   0.0  0.4161  8.034   31.9  5.1180   4.0  224.0
 ..        ...   ...    ...   ...     ...    ...    ...     ...   ...    ...
 345   0.03113   0.0   4.39   0.0  0.4420  6.014   48.5  8.0136   3.0  352.0
 460   4.81213   0.0  18.10   0.0  0.7130  6.701   90.0  2.5975  24.0  666.0
 46    0.18836   0.0   6.91   0.0  0.4480  5.786   33.3  5.1004   3.0  233.0
 80    0.04113  25.0   4.86   0.0  0.4260  6.727   33.5  5.4007   4.0  281.0
 400  25.04610   0.0  18.10   0.0  0.6930  5.987  100.0  1.5888  24.0  666.0

      PTRATIO       B  LSTAT
 304     18.4  393.68   6.93
 121     19.1  377.67  14.27
 337     20.2  394.81  10.56
 190     15.2  377.68   5.10
 204     14.7  390.55   2.88
 ..       ...     ...    ...
 345     18.8  385.64  10.53
 460     20.2  255.23  16.42
 46      17.9  396.90  14.15
 80      19.0  396.90   5.29
 400     20.2  396.90  26.77

 [102 rows x 13 columns],
 251    24.8
 422    20.8
 153    19.4
 178    29.9
 202    42.3
        ...
 259    30.1
 155    15.6
 409    27.5
 362    20.8
 113    18.7
 Name: price, Length: 404, dtype: float64,
 304    36.1
 121    20.3
 337    18.5
 190    37.0
 204    50.0
        ...
 345    17.5
 460    16.4
 46     20.0
 80     28.0
 400     5.6
 Name: price, Length: 102, dtype: float64]

In [41]:
#unpack all data
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=.2)

In [37]:
len(X_train)

404

In [38]:
len(X)*.8

404.8

In [39]:
len(X_train)+len(X_test)

506

In [42]:
# default shuffle is True henace it shuffles all data
X_train

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
129,0.88125,0.0,21.89,0.0,0.624,5.637,94.7,1.9799,4.0,437.0,21.2,396.90,18.34
172,0.13914,0.0,4.05,0.0,0.510,5.572,88.5,2.5961,5.0,296.0,16.6,396.90,14.69
480,5.82401,0.0,18.10,0.0,0.532,6.242,64.7,3.4242,24.0,666.0,20.2,396.90,10.74
57,0.01432,100.0,1.32,0.0,0.411,6.816,40.5,8.3248,5.0,256.0,15.1,392.90,3.95
165,2.92400,0.0,19.58,0.0,0.605,6.101,93.0,2.2834,5.0,403.0,14.7,240.16,9.81
...,...,...,...,...,...,...,...,...,...,...,...,...,...
277,0.06127,40.0,6.41,1.0,0.447,6.826,27.6,4.8628,4.0,254.0,17.6,393.45,4.16
130,0.34006,0.0,21.89,0.0,0.624,6.458,98.9,2.1185,4.0,437.0,21.2,395.04,12.60
18,0.80271,0.0,8.14,0.0,0.538,5.456,36.6,3.7965,4.0,307.0,21.0,288.99,11.69
98,0.08187,0.0,2.89,0.0,0.445,7.820,36.9,3.4952,2.0,276.0,18.0,393.53,3.57
265,0.76162,20.0,3.97,0.0,0.647,5.560,62.8,1.9865,5.0,264.0,13.0,392.40,10.45

In [47]:
# if we set shuffle = False
# then it will take data from top to bottom
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=.2,shuffle=False)

In [49]:
X_train[:5]

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33

In [87]:
# shuffle the data but only ones
# use random_state = 42
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=.2)

In [88]:
X_train[:4]

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
177,0.05425,0.0,4.05,0.0,0.510,6.315,73.4,3.3175,5.0,296.0,16.6,395.60,6.29
328,0.06617,0.0,3.24,0.0,0.460,5.868,25.8,5.2146,4.0,430.0,16.9,382.44,9.97
386,24.39380,0.0,18.10,0.0,0.700,4.652,100.0,1.4672,24.0,666.0,20.2,396.90,28.28
411,14.05070,0.0,18.10,0.0,0.597,6.657,100.0,1.5275,24.0,666.0,20.2,35.05,21.22

In [89]:
# apply algorithm to check score of data
from sklearn.linear_model import LinearRegression
model= LinearRegression()
#training
model.fit(X_train,y_train)
#check score of training data
model.score(X_train,y_train)*100

75.65121159309605

In [91]:
model.predict([[1.2,0,14.3,0,.45,4.5,15,2.1,11.2,344,12,100,9.8]])

array([25.40298905])

In [95]:
y_pred = model.predict(X_test)
y_pred

array([21.45086169, 19.29302767, 23.87950879, 23.43424307, 26.00892953,
       18.9332928 , 25.74322861, 22.9123431 , 16.27183953, 15.86950005,
       34.11369898, 38.94533779, 24.75553165, 30.76610286, 25.03288639,
       11.82846213, 10.26221815, 20.16827976, 10.03167189, 25.22695608,
       22.49606343,  4.40296938, 18.30145514, 14.38788205, 24.83765237,
       14.97252961, 30.53380599, 28.64149501, 22.73060313, 17.92070503,
       16.97182218, 18.17272979, 13.42729036, 31.37376937, 23.0308242 ,
       14.55983433, 15.00059146, 25.62252148, 27.10758207, 17.74781246,
       36.1455286 , 16.95568064, 30.86369476, 36.08554494, 34.64032427,
       21.2703475 , 41.55473728, 18.56488732, 21.66327212, 25.75436724,
       15.04902555, 31.44795018, 20.52513652, 20.59137932, 23.81347053,
       19.17998765, 27.81966063, 22.06301136, 20.58729805, 21.50107407,
       11.29397183, 22.3625048 , 17.63660873, 10.68019565, 13.79450501,
       32.26219309, 19.36068317, 33.27431517, 14.95751098, 19.07483314,
       30.70342387, 23.9564836 , 32.31677994, 27.26625057, 29.06377511,
       28.02832497, 28.48467411, 13.67233778, 17.8110381 , 17.50179008,
       35.08486643, 24.24700425, 30.67358167, 10.42250218, 19.53497792,
       21.65494139, 24.21493205, 13.08170432, 16.2413606 , 39.65655465,
       27.22881367, 33.61967988, 21.64362199, 25.12666577, 17.43893779,
       18.70811919, 30.23104618,  7.77836792, 29.14877185, 22.83833997,
       20.82520629, 13.69243464])

In [96]:
y_test

319    21.0
132    23.0
164    22.7
501    22.4
82     24.8
       ...
489     7.0
302    26.4
212    22.4
46     20.0
245    18.5
Name: price, Length: 102, dtype: float64